version: '3.8'

services:
  ktane-solver-db:
    image: postgres:16
    environment:
      POSTGRES_DB: ktane-solver
      POSTGRES_USER: ktane-solver
      POSTGRES_PASSWORD: ktane-solver
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: